### ISSUE TITLE
any help to solve this warning: `Symbol's value as variable is void: macrostep-mode-map`, please?

### ISSUE THREAD

**Issue by touxstone** [emacsorphanage/macrostep#10]
Hi, everyone
I have run into an issue when starting Emacs that makes some key behaviours fail to load correctly. When debugging with `emacs -debug-init` I got this warning: `Symbol's value as variable is void: macrostep-mode-map`. I have installed the current version of `macrostep` which reads 9.2, and supposedly corrects the obsolete-variable-alias `macrostep-mode-keymap` to  `macrostep-mode-map` but still. Would anyone know to tell how to solve this issue, please?
I would appreciate it.

**Comment by jflude** [comment]
Related: as of a few days ago I now get `Symbol's value as variable is void: macrostep-mode-map` as an error when installing `sly-macrostep` package on Emacs 27.1 (but it works fine on 29.3; both installations using `macrostep-20240328.2134` and`sly-macrostep-20191211.1630`)

**Comment by touxstone** [comment]
> Related: as of a few days ago I now get `Symbol's value as variable is void: macrostep-mode-map` as an error when installing `sly-macrostep` package on Emacs 27.1 (but it works fine on 29.3; both installations using `macrostep-20240328.2134` and`sly-macrostep-20191211.1630`)

I'm going on `GNU Emacs 28.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8) of 2023-09-24`

**Comment by touxstone** [comment]
> Related: as of a few days ago I now get `Symbol's value as variable is void: macrostep-mode-map` as an error when installing `sly-macrostep` package on Emacs 27.1 (but it works fine on 29.3; both installations using `macrostep-20240328.2134` and`sly-macrostep-20191211.1630`)

I'm going on `GNU Emacs 28.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8) of 2023-09-24`

**Comment by touxstone** [comment]
I have not closed "as completed" (sorry)
