### ISSUE TITLE
The now required function ‘defvar-keymap’ is only available since emacs 29

### ISSUE THREAD

**Issue by mlampe** [emacsorphanage/macrostep#11]
Updating from 0.92 to 0.93 with emacs 28.2 gives me:
```
macrostep-c.el:46:1: Error: Symbol’s function definition is void: defvar-keymap
```
Loading the `compat` package before installing fixes this. It should probably be a requirement now.

**Comment by mmontone** [comment]
Can this be relased please? SLIME is broken because of this for Emacs < 29. And I imagine other packages too ...
