### ISSUE TITLE
The `macrostep-mode` keybindings are not working!

### ISSUE THREAD

**Issue by abougouffa** [emacsorphanage/macrostep#4]
Hello,

Recently (one or two days ago), a change was made in the package which broke the `macrostep-mode` keybindings. After calling `macrostep-expand`, the defined keys (`e`, `q` and the others) do not work as pretended. I've verified the problem with `emacs -Q` on Emacs 29.0.60:

- Run `emacs -Q`;
- Evaluate this:
```elisp
(use-package macrostep
  :ensure t)
```
- Move the cursor to `use-package` for example;
- `M-x macrostep-expand`;
- Press `q`.

**Comment by ssl19** [comment]
According to doctring of define-minor-mode:
> :keymap MAP	Keymap bound to the mode keymap.  Defaults to ‘MODE-map’.

The :keymap line could be only omitted when the keymap variable name is `macrostep-mode-map`.

**Comment by justbur** [comment]
See #6. Changing the name of the keymap itself will cause issues with peoples' configs.

**Comment by ssl19** [comment]
Firstly, I didn't suggest that we should change the variable name.

Besides, `macrostep-mode-keymap` was added in commit c20f621bf2651aaf0f5c3e910b672ae859ebf126, which also removed `:keymap` and caused current issue. So I don't think change the name will matter.

**Comment by abougouffa** [comment]
I've already opened a PR (#5) which fixes this. I agree with @ssl19, the `macrostep-mode-keymap` was added recently and the old `macrostep-keymap` was made obsolete. We can adopt the *standard* way of naming mode keymaps, as: `macrostep-mode-map`.

**Comment by nverno** [comment]
bump
Needing to change the keymap name in library on each install currently, would be nice to merge this :+1:

**Comment by PhilHudson** [comment]
> bump Needing to change the keymap name in library on each install currently, would be nice to merge this +1

@nverno I read that as meaning you are going into the downloaded `.el` file and editing it, is that correct? If so, please share the diff.

**Comment by nverno** [comment]
@PhilHudson see https://github.com/emacsorphanage/macrostep/commit/c20f621bf2651aaf0f5c3e910b672ae859ebf126#r108633883

**Comment by tarsius** [comment]
Fixes in v0.9.2, by renaming the keymap again. This time to the expected name.
